call pathogen#infect()
call pathogen#helptags()

" use indent plugins from ./vim/indent directory
filetype indent plugin on
   
" miniBufferExplorer settings 
let g:miniBufExplMapWindowNavVim = 1
let g:miniBufExplMapWindowNavArrows = 1
let g:miniBufExplMapCTabSwitchBufs = 1
let g:miniBufExplModSeltarget = 1

" enable tags for CtrlP
let g:ctrlp_extensions = ['tag']
let g:ctrlp_custom_ignore = 'build'

" convinient navigation between windows
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" zz - Closes all but current buffer
nmap <silent> zz :BufOnly<CR>

" GUI setup
colorscheme desert
set guifont=Monospace\ 7

" Use 4 spaces for indentation by default
set shiftwidth=4
set tabstop=4
set softtabstop=4
set expandtab

nmap <F7> :make
