call pathogen#infect()
call pathogen#helptags()

syntax on
filetype plugin indent on

set number
set tabstop=4 shiftwidth=4 expandtab

let g:miniBufExplMapWindowNavVim = 1
let g:miniBufExplMapWindowNavArrows = 1
let g:miniBufExplMapCTabSwitchBufs = 1
let g:miniBufExplModSeltarget = 1

nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

nmap <silent> zz :BufOnly<CR>

set tags=./tags;/

colorscheme desert
set guifont=Monospace\ 7

nmap <F7> :make
